
package user.wssoap.nixsolutions.com;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserSoap", targetNamespace = "com.nixsolutions.wsSoap.user")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns user.wssoap.nixsolutions.com.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserByLogin", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.FindUserByLogin")
    @ResponseWrapper(localName = "findUserByLoginResponse", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.FindUserByLoginResponse")
    @Action(input = "com.nixsolutions.wsSoap.user/UserSoap/findUserByLoginRequest", output = "com.nixsolutions.wsSoap.user/UserSoap/findUserByLoginResponse")
    public User findUserByLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns user.wssoap.nixsolutions.com.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserByEmail", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.FindUserByEmail")
    @ResponseWrapper(localName = "findUserByEmailResponse", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.FindUserByEmailResponse")
    @Action(input = "com.nixsolutions.wsSoap.user/UserSoap/findUserByEmailRequest", output = "com.nixsolutions.wsSoap.user/UserSoap/findUserByEmailResponse")
    public User findUserByEmail(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns user.wssoap.nixsolutions.com.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserById", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.FindUserById")
    @ResponseWrapper(localName = "findUserByIdResponse", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.FindUserByIdResponse")
    @Action(input = "com.nixsolutions.wsSoap.user/UserSoap/findUserByIdRequest", output = "com.nixsolutions.wsSoap.user/UserSoap/findUserByIdResponse")
    public User findUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<user.wssoap.nixsolutions.com.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllUsers", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.FindAllUsers")
    @ResponseWrapper(localName = "findAllUsersResponse", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.FindAllUsersResponse")
    @Action(input = "com.nixsolutions.wsSoap.user/UserSoap/findAllUsersRequest", output = "com.nixsolutions.wsSoap.user/UserSoap/findAllUsersResponse")
    public List<User> findAllUsers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.CreateUserResponse")
    @Action(input = "com.nixsolutions.wsSoap.user/UserSoap/createUserRequest", output = "com.nixsolutions.wsSoap.user/UserSoap/createUserResponse")
    public void createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeUser", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.RemoveUserResponse")
    @Action(input = "com.nixsolutions.wsSoap.user/UserSoap/removeUserRequest", output = "com.nixsolutions.wsSoap.user/UserSoap/removeUserResponse")
    public void removeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "com.nixsolutions.wsSoap.user", className = "user.wssoap.nixsolutions.com.UpdateUserResponse")
    @Action(input = "com.nixsolutions.wsSoap.user/UserSoap/updateUserRequest", output = "com.nixsolutions.wsSoap.user/UserSoap/updateUserResponse")
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
